Ferreteria/Controllers/DetalleVentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;


namespace Ferreteria.Controllers
{
    public class DetalleVentaController : Controller
    {
       
        [HttpGet]
        public ActionResult Index(int id)
        {
            
            List<DetalleV> listaDetalleV = DetalleV.ListarID(id);
            return View(listaDetalleV);

        }
      
        public ActionResult AgregarDetalle(int id)
        {
           
            DetalleV detalle = new DetalleV();
            detalle.IdVenta = id;
            return View(detalle);

        }


        public ActionResult ListadoProductos()
        {
            //return View(new List<Producto>());
            return View(new List<DetalleV>());
        }

        //public ActionResult AgregarProducto(int id,int cantidad)
        //{
        //    //Obtener el producto            

        //    if (Session["ListaDetalleV"] == null)
        //    {
        //        List<DetalleV> ListaDetalleV = new List<DetalleV>();
        //        DetalleV detalleV = new DetalleV();
        //        //AgregarProducto producto = Producto.Obtener(id);
        //        detalleV.CantidadProd = cantidad;
        //        //detalleV.IdProducto = producto.IdProducto;
        //        //detalleV.Importe = producto.Importe;

        //        ListaDetalleV.Add(detalleV);
        //        Session["ListaDetalleV"] = ListaDetalleV;
        //    }
        //    else
        //    {
        //        List<DetalleV> ListaDetalleV =  (List<DetalleV>) Session["ListaDetalleV"];

        //        if(ListaDetalleV.Any(x =>x.IdProducto== id))
        //        {
        //            DetalleV DetalleVDuplicado = ListaDetalleV.Where(x => x.IdProducto == id).FirstOrDefault();
        //            DetalleVDuplicado.CantidadProd = DetalleVDuplicado.CantidadProd + cantidad;
        //            ListaDetalleV.Remove(ListaDetalleV.Where(x => x.IdProducto == id).FirstOrDefault());
        //            ListaDetalleV.Add(DetalleVDuplicado);
        //            Session["ListaDetalleV"] = ListaDetalleV;
        //        }
        //        else
        //        {
        //            DetalleV detalleV = new DetalleV();
        //            //AgregarProducto producto = Producto.Obtener(id);
        //            detalleV.CantidadProd = cantidad;
        //            //detalleV.IdProducto = producto.IdProducto;
        //            //detalleV.Importe = producto.Importe;
        //            ListaDetalleV.Add(detalleV);
        //            Session["ListaDetalleV"] = ListaDetalleV;
        //        }
        //    }
        //    return View("Index");
        //}


        //public ActionResult Editar(int? id)
        //{

        //    if (id == null)
        //    {
        //        DetalleV detallev = new DetalleV();

        //        return View(detallev);
        //    }
        //    else
        //    {
        //        // o uso el obtener pasando el id
        //        DetalleV DetalleV = DetalleV.Listar().Where(x => x.IdDetalleV == id).FirstOrDefault();
        //        return View(DetalleV);
        //    }
        //}

        [HttpPost]
        public JsonResult Editar(DetalleV detallev)
        {

            detallev.Grabar();
            Resultado resultado = new Resultado();
            resultado.EsCorrecto = true;
            resultado.Mensaje = "";
            return Json(detallev);

        }

        [HttpPost]
        public JsonResult CrearDetalle(int id)
        {
            Resultado resultado = new Resultado();
            DetalleV DetalleV = new DetalleV();

            try
            {
                DetalleV.IdVenta = id;
                DetalleV.IdProducto = Convert.ToInt32(Request.Form["IdProducto"]);
                DetalleV.CantidadProd = Convert.ToInt32(Request.Form["CantidadProd"]);         
                DetalleV.PrecioUnitario = Convert.ToDecimal(Request.Form["PrecioUnitario"]);
                DetalleV.Importe = DetalleV.CantidadProd * DetalleV.PrecioUnitario;
                DetalleV.Grabar();
                resultado.EsCorrecto = true;
                resultado.Mensaje = "";
            }
            catch (Exception ex)
            {
                resultado.EsCorrecto = false;
                resultado.Mensaje = ex.Message;
            }
            return Json(DetalleV);
        }

        [HttpPost]
        public JsonResult Guardar(DetalleV DetalleV)
        { 
            Resultado resultado = new Resultado();

            try
            {
                DetalleV.Grabar();

                
                resultado.EsCorrecto = true;
                resultado.Mensaje = "";
               
            }
            catch (Exception ex)
            {
                resultado.EsCorrecto = false;
                resultado.Mensaje = ex.Message;
            } 
            return Json(DetalleV);
        }

       
        //public JsonResult Eliminar(int idProducto)
        //{
        //    try
        //    {
        //        List<DetalleV> ListaDetalleV = (List<DetalleV>)Session["ListaDetalleV"];
        //        ListaDetalleV.Remove(ListaDetalleV.Where(x => x.IdProducto == idProducto).FirstOrDefault());
        //        Session["ListaDetalleV"] = ListaDetalleV;

        //        return Json(new Resultado());
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new Resultado(ex.Message, ex.HResult));
        //    }

        //}
        [HttpPost]
        public JsonResult Eliminar(int id)
        {
            try
            {
                DetalleV.Eliminar(id);
                return Json(new Resultado());
            }
            catch (Exception ex)
            {
                return Json(new Resultado(ex.Message, ex.HResult));
            }

        }
    }
}

Ferreteria/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;


namespace Ferreteria.Controllers
{
    public class VentasController : Controller
    {


        //public ActionResult maestroDetalle()
        //{
        //    return View();
        //}


        //[HttpPost]
        //public ActionResult Add(Venta venta)
        //{
        //    Venta  Venta = new Venta();

        //    try
        //    {
                
        //        Venta.IdCliente = 1;
        //        Venta.Fecha = DateTime.Now;
        //        Venta.Descripcion = Request.Form["Descripcion"];
        //        Venta.Grabar();
        //        foreach (var v in Venta.Listar())
        //        {
        //            Venta oventa = new Venta();
        //            oventa.IdCliente = 1;
        //            oventa.Fecha = DateTime.Now;
        //            oventa.Descripcion = Venta.Descripcion;
        //            oventa.IdVenta = Venta.IdVenta;
                    
        //        }
        //        Venta.Grabar();

        //        ViewBag.Message = "Registro insertado";
        //        return RedirectToAction("maestroDetalle");
        //    }
        //    catch (Exception ex)
        //    {
        //        return View(venta);
        //    }

        //}



        public ActionResult Index()
        {

            return View(Venta.Listar());
        }

        public ActionResult Detalle(int id)
        {
             Venta Venta = Venta.ListarTot(id).Where(x => x.IdVenta == id).FirstOrDefault();
                return View(Venta);
        }

       


        public ActionResult IndexFinal(int id)
        {

            List<Venta> listatot = Venta.ListarTot(id);
          
            return View(listatot);
        }
        public ActionResult Informe()
        {
            return View();
        }

        public ActionResult CrearVenta(int? id)
        {
            if (id == null)
            {
                Venta Venta = new Venta();
                Venta.Fecha = DateTime.Now;
                Venta.IdCliente = 1;
                return View(Venta);
            }
            else
            {
                // o uso el obtener pasando el id
                Venta Venta = Venta.Listar().Where(x => x.IdVenta == id).FirstOrDefault();
                return View(Venta);
            }
        }

        [HttpPost]
        public JsonResult Guardar(Venta venta)
        {


            Resultado resultado = new Resultado();
            venta.Grabar();
           

            resultado.EsCorrecto = true;
            resultado.Mensaje = "";
            return Json(venta);
            //try
            //{
            //    Venta venta = new Venta();
            //    //verificara si la sessiones nula
            //    //venta.ListaDetalleV = (List<DetalleV>)Session["ListaDetalleV"];
            //    venta.Total = venta.ListaDetalleV.Sum(x => x.Importe);
            //    venta.Fecha = DateTime.Now;
            //    venta.IdCliente = 1;
            //    venta.Descripcion = "";
            //    venta.Grabar();

            //    //Session["ListaDetalleV"] = null;
            //    resultado.EsCorrecto = true;
            //    resultado.Mensaje = "";
            //}
            //catch (Exception ex)
            //{

            //    resultado.EsCorrecto = false;
            //    resultado.Mensaje = ex.Message;
            //}

            //return Json(resultado);
        }
            

        [HttpPost]
        public JsonResult CrearV()
        {
            
            Venta venta = new Venta();

            venta.IdCliente = 1;
            venta.Fecha = DateTime.Now;
            venta.Descripcion = Request.Form["Descripcion"];

            if (venta.Total != 0)
            {
                venta.Total = venta.ListaDetalleV.Sum(x => x.Importe);
            }
            else
            {
                venta.Total = Convert.ToDecimal(Request.Form["Total"]);
            }

            venta.Grabar();
            

            Resultado resultado = new Resultado();

            resultado.EsCorrecto = true;
            resultado.Mensaje = "";
            return Json(venta);
        }

        
        [HttpPost]
        public JsonResult Eliminar(int id)
        {
            try
            {
               Venta.Eliminar(id);
                return Json(new Resultado());
            }
            catch (Exception ex)
            {
                return Json(new Resultado(ex.Message, ex.HResult));
            }

        }


    }

    

}

Ferreteria/Views/Ventas/CrearVenta.cshtml
@{ Layout = null; }


@model Tuple<Negocio.Venta, Negocio.DetalleV>

@{
    ViewBag.Title = "Crear";
}

<link href="~/EstiloFerreteria1/css/sb-admin-2.css" rel="stylesheet" />
<script src="~/EstiloFerreteria1/js/sb-admin-2.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="/DataTables/datatables.css">
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/Ventas/ABM.js"></script>
<script src="~/Scripts/Ventas/sweetalert.js"></script>

<style>
    td {
        padding: 10px;
    }

    input[type="checkbox"] {
        width: 20px;
        height: 20px;
        margin-left: 5px;
        vertical-align: middle;
    }
</style>


<div class="container">
    <h3>Generar nueva venta:</h3>
    <br />
    <form action="/Ventas/Guardar" id="FrmVenta" method="post">
        <table>
            <tr>
                <td style="text-align: right">Numero de Venta:</td>
                <td><input class="form-control" style="width: 350px" type="text" value="#" readonly="readonly" required /></td>
                <td style="text-align: right">Cliente:</td>
                <td><input class="form-control" style="width: 350px" value="Consumidor Final" type="text" readonly="readonly" required /></td>
            </tr>
            <tr>
                <td style="text-align: right">Fecha:</td>
                <td><input class="form-control" type="date" name="Fecha" id="Fecha" readonly="readonly" required /></td>
                <td style="text-align: right">Descripcion:</td>
                <td><input class="form-control" type="text" name="Descripcion" id="Descripcion" required /></td>
            </tr>
        </table>
        <br /><br />

        <div class="btn btn-primary btn-md" onclick="CrearVenta()">CREAR</div>

        <br />
        <br />
    </form>


    <hr>
    <form  action="/DetalleVenta/Guardar" id="FrmDetalle" method="post">
        <div class="row">
            <div class="form-group col-md-4">
                <label>IdProducto</label>
                <input type="number" class="form-control" name="IdProducto" asp-for="Item2.Cantidad">
                <span asp-validation-for="Item2.IdProducto"></span>
            </div>
            <div class="form-group col-md-4">
                <label>Cantidad</label>
                <input type="text" class="form-control" name="CantidadProd" asp-for="Item2.Cantidad">
                <span asp-validation-for="Item2.Cantidad"></span>
            </div>
            <div class="form-group col-md-4">
                <label>Precio</label>
                <input type="text" class="form-control" asp-for="Item2.Precio">
                <span asp-validation-for="Item2.Precio"></span>
            </div>
            <div class="form-group col-md-4">
                <label>Importe</label>
                <input type="text" class="form-control" name="Importe" asp-for="Item2.Precio" readonly="readonly">
                <span asp-validation-for="Item2.Precio"></span>
            </div>
        </div>
        <div class="row">
            <button type="submit" class="btn btn-primary">GUARDAR</button>
        </div>
    </form>



    <br /><hr />
    <div class="btn btn-default">
        @Html.ActionLink("Atrás", "Index")
    </div>
</div>

Ferreteria/Views/Ventas/Detalle.cshtml
@{ Layout = null; }
@model Negocio.Venta

@{
    ViewBag.Title = "Detalle";
}
<link href="~/EstiloFerreteria1/css/sb-admin-2.css" rel="stylesheet" />
<script src="~/EstiloFerreteria1/js/sb-admin-2.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="/DataTables/datatables.css">
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/Ventas/ABM.js"></script>
<script src="~/Scripts/Ventas/sweetalert.js"></script>


@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "FrmVenta" }))
{
    @Html.AntiForgeryToken()

<div class="container">

    <div class="form-horizontal">
        <div class="cont">
            <h3>Venta - Finalizar</h3>
            <hr />
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-4">N. Venta</label>
            <div class="col-md-2">
                @Html.EditorFor(model => model.IdVenta, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.IdVenta, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-4">Cliente</label>
            <div class="col-md-2">
                <input type="text" name="IdCliente" value="Consumidor Final" class="form-control" readonly="readonly">

                @*@Html.EditorFor(model => model.IdCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdCliente, "", new { @class = "text-danger" })*@
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                <br />
                <div class="btn btn-success" onclick="EditarVenta()">Finalizar Venta</div>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">

                <div style="margin:initial">
                    <a class="btn btn-primary btn-sm" href="/DetalleVenta/AgregarDetalle/@Model.IdVenta" title="Agregar detalle">Vovler</a>

                </div>

            </div>
        </div>
    </div>
</div>
    }

Ferreteria/Views/Ventas/DetalleVenta.cshtml
@{ Layout = null; }
@model Negocio.DetalleV

@{
    ViewBag.Title = "Detalle";
}

<link href="~/EstiloFerreteria1/css/sb-admin-2.css" rel="stylesheet" />
<link href="~/EstiloFerreteria1/css/personalizado.css" rel="stylesheet" />


<div class="card-body">
    <div class="table-responsive">
        <div class="container">
            <h4 class="text-center">Venta</h4>
            <hr /></br>

            <table>
                <caption>Detalle de la Venta</caption>
                <thead>
                    <tr>
                        <th>N°Venta</th>
                        <th>Cod.Producto</th>
                        <th>Cantidad</th>
                        <th>Precio Unitario</th>


                        <th>Importe</th>
                    </tr>
                </thead>
                @foreach (Negocio.DetalleV item in Negocio.DetalleV.ListarID(Model.IdVenta))
                {
                    <tfoot>

                        <tr>
                            <td colspan="4">TOTAL</td>
                            <td>@Html.DisplayFor(model => model.Importe)</td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.IdDetalleV)</td>
                            <td>@Html.DisplayFor(model => model.IdVenta)</td>
                            <td>@Html.DisplayFor(model => model.IdProducto)r</td>
                            <td>@Html.DisplayFor(model => model.CantidadProd)</td>
                            <td>@Html.DisplayFor(model => model.PrecioUnitario)</td>

                        </tr>

                    </tbody>
                }


            </table>

            <div class="container">

                <a href="/Ventas/Index">
                    <input type="button" class="btn btn-primary btn-sm " value="Atrás">

                </a>

            </div>

        </div>
    </div>
</div>

Ferreteria/Views/Ventas/Informe.cshtml
@{ Layout = null; }
@{
    ViewBag.Title = "Informe";
}


<link href="~/EstiloFerreteria1/css/sb-admin-2.css" rel="stylesheet" />
<link href="~/EstiloFerreteria1/css/personalizado.css" rel="stylesheet" />
<link href="~/Content/alert.css" rel="stylesheet" />
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="~/Scripts/Ventas/sweetalert.js"></script>
<br />

<div class="container">
    <h2>Informe</h2>
    <hr />
    <br />
    <form action="/Ventas/InformeGuardar" id="FrmVenta" method="post">

        <label>Ingrese un mes:</label>
        <input class="form-control" style="width: 250px" type="number" placeholder="ejemplo 01 como enero..." name="Fecha" id="Fecha" required />
        <br />


        <a class="btn btn-success" href="/Ventas/CrearVenta"> Obtener Informe</a>
        <a class="btn btn-danger" href="/Ventas/Index"> Salir</a>



    </form>
</div>

Ferreteria/Views/Ventas/maestroDetalle.cshtml
@{ Layout = null; }

@model Negocio.Venta
@{
    ViewBag.Title = "maestroDetalle";
}

<h2>maestroDetalle</h2>
<div style="color:aquamarine">
    @ViewBag.Mesagge
</div>

@using (Html.BeginForm("Add", "Ventas", FormMethod.Post))
{

    <div class="row">
        <div>
            @Html.LabelFor(model => model.IdVenta)
            @Html.TextBoxFor(model => model.IdCliente)
        </div>
        <div class="form-group">
            <input type="submit">

        </div>
        <hr />
        <div class="row">
            <div class="form-group">
                IdCliente
                <input type="number" id="IdCliente" />
                Fecha
                <input type="date" id="Fecha" />
                Descripcion
                <input type="text" id="Descripcion" />
                <input value="Agregar" type="button" onclick="Agregar(); return false;"/>
            </div>



            <div id="divConcepto">
                <table id="tablaVenta">
                    <tr>
                        <th>N°Venta</th>
                        <th>Id Cliente</th>
                        <th>Fecha</th>
                        <th>Descripcion</th>

                    </tr>
                    <tr>
                        <th>1</th>
                        <th>2</th>
                        <th>20-39-2222</th>
                        <th>Varios</th>

                    </tr>

                </table>

                <input type="hidden" name="Ventas.maestroDetalle" id="Ventas.maestroDetalle" value="0" />
               
                <input type="hidden" name="Ventas[0].IdCliente" id="Ventas[0].IdCliente" value="2" />
                <input type="hidden" name="Ventas[0].Fecha" id="Ventas[0].Fecha" value="20-39-2222" />
                <input type="hidden" name="Ventas[0].Descripcion" id="Ventas[0].Descripcion" value="varios" />


            </div>

        </div>

       
    </div>
}

    <script>
        function Agregar() {

            let IdCliente = document.getElementById("IdCliente").value;
            let Fecha = document.getElementById("Fecha").value;
            let Descripcion = document.getElementById("Descripcion").value;

            let tabla = document.getElementById("tablaVenta");
            let TR = document.createElement("tr");
            let TDIdCliente = document.createElement("td");
            let TDFecha = document.createElement("td");
            let TDDescripcion = document.createElement("td");
            TR.appendChild(TDIdCliente);
            TR.appendChild(TDFecha);
            TR.appendChild(TDDescripcion);
            TDIdCliente.innerHTML = IdCliente;
            TDFecha.innerHTML = Fecha;
            TDDescripcion.innerHTML = Descripcion;

            tabla.appendChild(TR);

            let divConcepto = document.getElementById("divConceptos");
            let HiddenIndex = document.getElementById("input");
            let HiddenIdCliente = document.getElementById("input");
            let HiddenFecha = document.getElementById("input");
            let HiddenDescripcion = document.getElementById("input");


            HiddenIndex.name = "Ventas.maestroDetalle";
            HiddenIndex.value = num;
            HiddenIndex.type = "hiden";
            HiddenIdCliente.name = "Ventas[" + num + "].IdCliente";
            HiddenIdCliente.value = IdCliente;
            HiddenIdCliente.type = "hiden";
            HiddenFecha.name = "Ventas[" + num + "].Fecha";
            HiddenFecha.value = Fecha;
            HiddenFecha.type = "hiden";
            HiddenDescripcion.name = "Ventas[" + num + "].Descripcion";
            HiddenDescripcion.value = Descripcion;
            HiddenDescripcion.type = "hiden";
            divConcepto.appendChild(HiddenIndex);
            divConcepto.appendChild(HiddenIdCliente);
            divConcepto.appendChild(HiddenFecha);
            divConcepto.appendChild(HiddenDescripcion);




            let IdCliente = document.getElementById("IdCliente").value = "";
            let Fecha = document.getElementById("Fecha").value="";
            let Descripcion = document.getElementById("Descripcion").value="";
        }

    </script>